### ISSUE TITLE
Unable to Upload

### ISSUE THREAD

**Issue by adamchow** [stfnhmplr/pagekit-gallery#10]
Trying to get this extension working. I've haven't been able to make this work on multiple installations on different servers. I keep getting the error below when trying to upload images to the gallery (.jpeg format).

`TypeError: this.form.delete is not a function. (In 'this.form.delete('images[item]')', 'this.form.delete' is undefined)
upload — gallery-images.js:467
Selected Element
<input id="file-input" type="file" name="files" multiple="multiple" accept="image/jpeg,image/png">
`

Any help with this would be great. I feel like I'm missing something or something in gallery-images.js is conflicting with another script.

Also tried it with a clean install of the latest pagekit with no other extensions installed. No go.

**Comment by stfnhmplr** [comment]
Thanks for feedback. Which browser do you use?

**Comment by twistedonion** [comment]
Getting that issue in Safari v10 myself. Fine in Chrome

**Comment by adamchow** [comment]
I'm using Safari v10 as well. Just tried it in Chrome Version 54.0.2840.71 (64-bit) and it works. 

Let me know if you want me to run some tests on your next commits and further debug it in Safari.

**Comment by stfnhmplr** [comment]
Safari doesn't support some formData operations. i changed the upload function. works for me with safari. maybe you can test it too and give a short feedback. thanks in advance.

**Comment by hustla214** [comment]
I have a similar or same problem.

I create a gallery and save it. Then i go to the images section and drag the files into my Safari browser but when i hit the upload button nothing happens. Debug shows this error message: this.form.delete is not a function. (In 'this.form.delete('images[item]')', 'this.form.delete' is undefined)

How can i solve this issue? Would appreciate any help...

**Comment by stfnhmplr** [comment]
update is published and the upload issue is fixed. you can update to version 0.2.4 at the marketplace.
