### ISSUE TITLE
getting "Images not found" on page

### ISSUE THREAD

**Issue by roarkmccolgan** [stfnhmplr/pagekit-gallery#12]
Hi,

I was able to create the gallery, upload images and it exists on the server and an entry in the database but I get "Images not found" on the page where I include the gallery.

Thanks!

**Comment by stfnhmplr** [comment]
Thanks for your feedback. Can you check the gallery id at the shortcode? i think it is the wrong gallery id. should look like this `[gallery id="9" limit="2" showLink="true"/]` maybe you can edit the id by hand. update ist already commited.

**Comment by roarkmccolgan** [comment]
Hi @stfnhmplr, I did manually edit the gallery_id value. However I still get the same error.

in "SlideshowPlugin.php" I dumped $query->get() after manually adding the gallery_id and I get a result from the database however the statement **if($images = $query->get())** still returns false.

Any ideas?

**Comment by roarkmccolgan** [comment]
Wait a minute!!!!! I think I worked it out...

I think there is a problem with the regular expressions used to create the attributes array:
My shortcode looks like this in the article:
`[gallery id="1" limit="" showLink="false"/]`
After regex the attributes array looks ike this:
`Array
(
    [id] => 1
    [showLink] => 
    [limit] => " showLink=
)`
The issue is **limit** intval() on `" showLink=` will return 0 and so the query is limiting itself to 0 and hence returning false on ->get()

Thanks!

**Comment by stfnhmplr** [comment]
Not really. Can you remove the dump and the if/else and only run '$images = $query->get();' and '$content = str_replace($matches[0][$key], App::view('gallery:views/slideshow.php', compact('images', 'attributes', 'gallery')), $content);'?

**Comment by stfnhmplr** [comment]
fixed. maybe you can test it again and give me a feedback.

**Comment by roarkmccolgan** [comment]
How do I update the extention in pagekit?
the version in marketplace is still 0.2.3-beta and when I try manually installing the zip file from control panel I get the error `Can't load json file from package.`

Thanks!

**Comment by stfnhmplr** [comment]
update is published. you can update to version 0.2.4 at the marketplace.
