### ISSUE TITLE
Unable to find gallery css file

### ISSUE THREAD

**Issue by roarkmccolgan** [stfnhmplr/pagekit-gallery#13]
Hi,

The page is unabe ot find the css file, it is trying to load:
"**[MYURL]**/extensions/gallery/assets/css/gallery.css"

and getting 404 not found

**Comment by stfnhmplr** [comment]
thanks, it was the wrong path. will be fixed with the next update

**Comment by roarkmccolgan** [comment]
Great, Thanks @stfnhmplr!

Will do

**Comment by roarkmccolgan** [comment]
Hey @stfnhmplr 

Just confirming that the css file `packages/shw/gallery/assets/css/gallery.css` is supposed to be empty?

**Comment by stfnhmplr** [comment]
yes, for now. maybe i will create a custom style for the frontend in the future.
