### ISSUE TITLE
slideshow.php missing script path

### ISSUE THREAD

**Issue by roarkmccolgan** [stfnhmplr/pagekit-gallery#14]
Hey @stfnhmplr 
Just noticed that the path to the minigallery script referenced in slideshow.php is blank:
`<?php $view->script('minigallery', '', ['uikit', 'uikit-slideshow']) ?>`

and hence the view loads the homepage as a script file and an exception is thrown.

Thanks!

**Comment by stfnhmplr** [comment]
fixed. thanks for your feedback

**Comment by roarkmccolgan** [comment]
Hi @stfnhmplr Thanks for working on the project,
I noticed the above line hasn't changed in `slideshow.php`

`<?php $view->script('minigallery', '', ['uikit', 'uikit-slideshow']) ?>`

What script should be loaded here?
Thanks

**Comment by stfnhmplr** [comment]
nothing, but i need to include uikit.js and uikit-slideshow.js and that is the cleanest way to do. i replaced it with an empty js file. the code is not published to the marketplace for. i have to fix the automatic uninstall first. you can grab it from this repository.

**Comment by stfnhmplr** [comment]
update is published. you can update to version 0.2.4 at the marketplace.
