### ISSUE TITLE
gallery not wrapped within article

### ISSUE THREAD

**Issue by burnziii** [stfnhmplr/pagekit-gallery#16]
Galery is not wrapped within <article class="uk-article"></article> so design looks a bit strange.

**Comment by stfnhmplr** [comment]
Sorry for my late response. What do you mean exactly? The view at the backend or the frontend? Or the slideshow? Maybe you can show a screenshot?

**Comment by stfnhmplr** [comment]
Hey there!

I close this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. If the issue still exists, let me know with a comment and i will reopen it.

Thanks!
