### ISSUE TITLE
Missing galleries after update.

### ISSUE THREAD

**Issue by xsurox** [stfnhmplr/pagekit-gallery#21]
After update from 0.2.4 to 0.2.5 - all galleries are gone from list - no edit possible.
Galleries are functional and visible on page.

....................
4 Galleries                                ADD GALLERY
NÁZOV	PHOTOGRAPH	STATUS 	AUTHOR 	DATE	URL
**No Galleries found**
......................

**Comment by stfnhmplr** [comment]
Hey. Looks like an issue at the backend. Can you clear the Browser cache and open the browser console? There should be an error message. Please post this message here.

**Comment by xsurox** [comment]
I have cleared browser cache, reloaded, checked - no error message in console.

**Comment by stfnhmplr** [comment]
I'm sorry. I can't reproduce this. I'd tried several updates but the galleries are still visible at the backend. I just published a new update to the marketplace. Maybe you can update your version and test again. You can also try another browser.
Last possibility is to give me access to your pagekit backend. Of course only for the gallery extension. Then I can take a look at this.

**Comment by xsurox** [comment]
@stfnhmplr    http://www.sfkovo.sk/admin        user: gallery  pass: github.com

**Comment by stfnhmplr** [comment]
Thanks. You can delete the user. Your galleries are visible again. In the settings there is an option "galleries per page". There was a value missing.

**Comment by xsurox** [comment]
Thank you, now it's OK.

**Comment by burnziii** [comment]
Had the same issue, would it be possible to make clear that there is no entry below 1 in the settings?
