### ISSUE TITLE
No Upload possible

### ISSUE THREAD

**Issue by diaman** [stfnhmplr/pagekit-gallery#26]
Hi Developer,

- GD bibliothek is installed
- all neccessary folders & files are writeable

but allthough i'm not able to import images. Error Message: 'Fehler beim Hochladen der Bilder'.
Gallery saving functionized, but image upload not. Any ideas? Many Thanx in advance, D.

**Comment by Sebastianalien** [comment]
Hi,

I have the same error, unable to load images. 

Version 0.2.6
Error Message: "Error while uploading images".

**Comment by diaman** [comment]
Ok, I found out: pagekit Gallery is installing a folder 'shw-gallery'. Saw this after a while..Give these folder rights to Import Images (770). Theater would bei all ;-)

**Comment by diaman** [comment]
..installing in folder 'storage'.

**Comment by diaman** [comment]
fuffy on rights combined with s.e..

**Comment by stfnhmplr** [comment]
I don't believe it's on rights. Each folder get's 755 on creation. Did you notice the max. upload size? Maybe you can test it with some small images.

**Comment by Sebastianalien** [comment]
I work perfectly.

Pozdrawiam 
Sebastian Rurarz

Wysłane z iPhone'a

Dnia 11.09.2017 o godz. 21:53 stfnhmplr <notifications@github.com> napisał(a):

**Comment by theofruitrouge** [comment]
Hi,
Same issue on prod server and local MAMP. Permissions are ok (775), tried under Pagekit 1.0.14 and 1.0.16. Tried with every PHP version from 5.6 until newest, tried with different browser (Firefox, Safari, Chromium & Chrome), Gallery extension is updated. Cannot figure out what's wrong...
