### ISSUE TITLE
Gallery Widget

### ISSUE THREAD

**Issue by BrightdayStudio** [stfnhmplr/pagekit-gallery#36]
Hi, I can't figure out how to add a gallery to an existing page. I made a new widget type, but what do I put into my template.php? Maybe something like:

<?= $view->render('gallery') ?>

**Comment by stfnhmplr** [comment]
There is a button at the editor to insert a gallery shortcode to a page or blog post. If you use TinyMCE you need at least version 0.3.0 for a menu entry.

**Comment by BrightdayStudio** [comment]
Got it! thanks I didn't see that.
