### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by barkahwibowo** [stfnhmplr/pagekit-gallery#5]
this error appears while i was trying to install pagekit-gallery

`Loading composer repositories with package information`
`Updating dependencies`
`Your requirements could not be resolved to an installable set of packages.`

what 'requirements' does pagekit-gallery need?
thanks

**Comment by stfnhmplr** [comment]
the gallery extension uses `gregwar/image` package and the gd image library. the `gregwar/image` package should be installed automatically. the gd image library must be included in your php installation.
