### ISSUE TITLE
Pictures don't appear

### ISSUE THREAD

**Issue by T-Zahil** [stfnhmplr/pagekit-gallery#6]
Hi, 

Great idea, I needed an extension like this.

Buuut the problem is that when I try to add pictures, they don't appear, both on the admin panel and the website.
Here is the console log when I try to add a picture : 

`vue.js?v=e232:1023 [Vue warn]: You are setting a non-existent path "form" on a vm instance. Consider pre-initializing the property with the "data" option for more reliable reactivity and better performance.warn @ vue.js?v=e232:1023
vue.js?v=e232:1023 [Vue warn]: Error when evaluating expression "gallery.data.meta['og:title']": TypeError: Cannot read property 'og:title' of undefined (found in component: <gallery-meta>)warn @ vue.js?v=e232:1023
vue.js?v=e232:1023 [Vue warn]: Error when evaluating expression "gallery.data.meta['og:description']": TypeError: Cannot read property 'og:description' of undefined (found in component: <gallery-meta>)warn @ vue.js?v=e232:1023
http://localhost:8888/storage/shw-gallery/thumbnails/tn_1474897776_orig_af1qippwrr6axt7mprq37vnt8upwxqzaeablngkxmavd.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/app/system/assets/images/placeholder-image.svg Failed to load resource: the server responded with a status of 404 (Not Found)
tinymce.jquery.min.js:1 Use tinymce.min.js instead of tinymce.jquery.min.js.
gallery-images.js?v=e232:493 750668: 750668
http://localhost:8888/storage/shw-gallery/thumbnails/tn_1474897936_orig_af1qipomlkfdlg79pt7l2erxfemdq0yzvqr-l2ucvwsi.jpg Failed to load resource: the server responded with a status of 404 (Not Found)`

Thanks in advance !

**Comment by stfnhmplr** [comment]
hi, thanks for your feedback. please try the following things:
- can you check the files in your `/storage/shw-gallery/thumbnails` folder? is the file `tn_1474897776_orig_af1qippwrr6axt7mprq37vnt8upwxqzaeablngkxmavd.jpg` in this folder?
- Please try to upload an image with a short filename like `image.jpg`
- have you installed the blog extension? Is there the placeholder image displayed when you create the a new post?

**Comment by T-Zahil** [comment]
Sure ! 

1/ Yes, there is the file tn_1474897776_orig_af1qippwrr6axt7mprq37vnt8upwxqzaeablngkxmavd.jpg in this folder. 
2/ Same thing append :/.
3/ Yes I have the blog extension, and there is a placeholder image if I choose one when I create a new post. 

This is the screen when I choose a gallery : https://puu.sh/rsYXM/e857afce5d.png

**Comment by stfnhmplr** [comment]
Are the images displayed at the frontend?
Looks like an url error. Please install this version manually and try again.
https://www.dropbox.com/s/dhe3mbd6anc7uqe/shw-gallery.zip?dl=0

**Comment by T-Zahil** [comment]
Sorry for the delay, I was busy on another project.

It work with your version, thank you ! Is there something I did wrong with pagekit ?

Thanks again :) !

**Comment by stfnhmplr** [comment]
no, my mistake. i had to use the url generator provided by pagekit for the image source.
thanks for your feedback.
